spring.application.name=notification-service
server.port=8086
spring.cloud.config.enabled=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

management.tracing.sampling.probability=1.0
management.tracing.zipkin.endpoint=http://zipkin:9411/api/v2/spans
