spring.application.name=api-gateway
server.port=8222
spring.cloud.config.enabled=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Auth Service
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/gateway/auth/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

# Catalog Service
spring.cloud.gateway.server.webmvc.routes[1].id=catalog-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://catalog-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/gateway/catalog/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=2

# Order Service cart
spring.cloud.gateway.server.webmvc.routes[2].id=order-service-cart
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://order-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/gateway/orders/cart/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=2

# Order Service orders
spring.cloud.gateway.server.webmvc.routes[3].id=order-service-orders
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://order-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/gateway/orders/orders/**
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=StripPrefix=2

# Admin Service
spring.cloud.gateway.server.webmvc.routes[4].id=admin-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://admin-service
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/gateway/admin/**
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=StripPrefix=2

management.tracing.sampling.probability=1.0
management.tracing.zipkin.endpoint=http://zipkin:9411/api/v2/spans

jwt.secret=ShopSphereSecretKey2024ShopSphereSecretKey2024ShopSphereSecretKey2024
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
