spring.application.name=admin-service
server.port=8085
spring.cloud.config.enabled=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

services.catalog-url=${SERVICES_CATALOG_URL:http://localhost:8083}
services.order-url=${SERVICES_ORDER_URL:http://localhost:8084}

management.tracing.sampling.probability=1.0
management.tracing.zipkin.endpoint=http://zipkin:9411/api/v2/spans

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
